### ISSUE TITLE
Omega8 version uses old version of patch in #1805690

### ISSUE THREAD

**Issue by jerbob92** [omega8cc/drupal7x#2]
The Omega8 version of 7.x uses an old patch of #1805690.
This old version of the patch (which is almost 3 years old), has an error which makes the file access handling broken. See [here](https://www.drupal.org/node/1805690#comment-8888941) for a description of why it's broken.

I think you should remove the patch or add the patch from comment #25.

**Comment by omega8cc** [comment]
Fixed in https://github.com/omega8cc/7x/commit/b8d4be9222182e637b901b9a841b66f53f82d3da and https://github.com/omega8cc/7x/commit/834198f0ede42351c6eb910faba0c136d809e858, thanks!

**Comment by omega8cc** [comment]
Referenced in https://github.com/omega8cc/boa/commit/a37c275ba351bd38e8ff235ec2f7cc870a7486a5

Thanks again!

**Comment by jerbob92** [comment]
Thanks for the quick response :+1:
