### ISSUE TITLE
Ajax callback

### ISSUE THREAD

**Issue by timlie** [omega8cc/drupal7x#3]
Hi,

When using your version of D7 something strange happens on an ajax callback.
After the ajax callback when the html is replaced, we are "redirected" to the bottom of the page.
I noticed this when using commerce and trying to make a manual order with the commerce line item manager. After clicking the "add line item" button, we get to the bottom of the page.
I tried with several sites. Where I use omega8cc's version of D7 this strange behaviour comes up.
When using vanilla D7 this does not happen.

Thanks!

**Comment by timlie** [comment]
The "problem" is coming from these extra lines in misc/ajax.js:

   // If the element that triggered the ajax request is still in the DOM and
   // visible, set the focus back to that element.
  if (this.form && this.element) {
    var $element = this.form.find('[name="' + this.element.name + '"]');
    if ($element.length !== 0 && $element.is(':visible')) {
      $element.focus();
    }
   }

After removing, problem is solved.

**Comment by omega8cc** [comment]
We may need to investigate which contributed patch introduced these lines (and why) before removing them.

**Comment by omega8cc** [comment]
BTW, this patch was a result of issue reported years ago: https://www.drupal.org/node/2124397

Let's revert if it causes unexpected side effects now.

**Comment by omega8cc** [comment]
https://github.com/omega8cc/7x/commit/e04de25ac3418d2c32de409d6f53f8b383de2e6a
