### ISSUE TITLE
Drupal 7.74 reports as 7.74-dev

### ISSUE THREAD

**Issue by VangelisP** [omega8cc/drupal7x#5]
On the latest release: http://files.aegir.cc/core/drupal-7.74.1.tar.gz

on `bootstrap.inc`, Drupal reports as : `define('VERSION', '7.74-dev');` on [line 11](https://github.com/omega8cc/7x/blob/7.x-om8/includes/bootstrap.inc#L11)

This unfortunately triggers wrong status messages as seen below:

![image](https://user-images.githubusercontent.com/14973113/100135150-2157e780-2e81-11eb-80c8-2d7afb6d2a24.png)

Here's how Drupal is being reported:

![image](https://user-images.githubusercontent.com/14973113/100135228-3cc2f280-2e81-11eb-922a-1e9ee4cdbbf6.png)

**Comment by omega8cc** [comment]
This has been fixed in the meantime with newer releases. Thank you for the report.
