### ISSUE TITLE
Drupal 7.91.1 / 7.92.1 release?

### ISSUE THREAD

**Issue by sluc23** [omega8cc/drupal7x#9]
@omega8cc  any estimation for 7.91.1 (or even 7.92.1) release? 
7.91 is a security upgrade, we should start using asap.

Would you accept PR if we work on that?

Thanks

**Comment by omega8cc** [comment]
7.92.1 is available now, thank you!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sluc23** [comment]
thank you!
